version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx-vault
    restart: on-failure
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
    ports:
      - "443:443"
